apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: par11t9hw-python 
  janus-idp.io/tekton: par11t9hw-python
  backstage.io/kubernetes-id: par11t9hw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: par11t9hw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml