apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: par11t9hw-python
  janus-idp.io/tekton: par11t9hw-python
  backstage.io/kubernetes-id: par11t9hw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: par11t9hw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
